select 
count( case when order_status='canceled' THEN 1 END) AS canceled_order,
count (case when order_status = 'delivered' THEN 1 END) AS delivered_order,
count (case when order_status = 'shipped' THEN 1 END) AS shipped_order
FROM ORDERS ;
select
count(case when freight_value >50 THEN 1 end) AS high_shipping,
count(case when freight_value<= 50 THEN 1 END) AS low_shipping              
from order_item
-- total revenue generated by each order
select order_id,sum(price+freight_value) AS total_revenue
from order_item
group by order_id;

select TOP 10 orders.customer_id, sum(order_item.price + order_item.freight_value) AS total_spending
from order_item
inner join orders on order_item.order_id = orders.order_id
group by orders.customer_id
order BY total_spending desc;

-- TOP 5 best selling products on the basis of quantity *********
SELECT TOP 5
product_id,
COUNT(product_id) AS total_quantity_sold
FROM order_item
GROUP BY product_id
ORDER BY total_quantity_sold DESC;

--total revenue generated by each product category
select product.product_category_name, sum(order_item.price + order_item.freight_value) AS to_revenue
from product
join order_item on
product.product_id = order_item.product_id
group by product.product_category_name
order by to_revenue desc;

--monthly revenue trend 
select year(orders.order_purchase_timestamp)AS order_year,
month(orders.order_purchase_timestamp)AS order_month,
sum(order_item.price + order_item.freight_value) AS total_revenue
from orders
join order_item on orders.order_id = order_item.order_id
group by year(orders.order_purchase_timestamp), month(orders.order_purchase_timestamp)
order by order_year, order_month ;

--/Classify customers into:
--total spending > 10000	High Value Customer
--otherwise Regular Customer                 
select customers.customer_id AS customer_id,
sum(order_item.price + order_item.freight_value) AS total_spending,
CASE 
when sum(order_item.price + order_item.freight_value) > 1000 then ' high value customer'
else 'regular customer'
END as customer_segment
from order_item
join orders on orders.order_id = order_item.order_id 
join customers on customers.customer_id = orders.customer_id
group by customers.customer_id;

-- create a CTE named customer_spending
 with customer_spending AS 
 (  select customers.customer_id AS customer_id,
sum(order_item.price + order_item.freight_value) AS total_spending
from order_item
join orders on orders.order_id = order_item.order_id 
join customers on customers.customer_id = orders.customer_id
group by customers.customer_id)
 
 select customer_id, total_spending,
 CASE 
  when total_spending> 1000
  then 'high value customer'
  else 'regular customer'
  end as customer_segment 
  from customer_spending;

 -- classify customers as:   | customer_id | total_orders | customer_type |
 -- total_orders>2 then frequent customers otherwise occasional customer

 with customer_orders as 
 ( select customers.customer_id AS customer_id,
   count(orders.order_id) as total_orders
   from customers
   join orders on customers.customer_id = orders.customer_id
   group by customers.customer_id )
    select customer_id, total_orders,
    CASE 
    when total_orders > 2 
    then 'frequent customer'
    else 'occasional customer'
    end AS customer_type 
    from customer_orders;

-- top 5 customer by total spending

with customer_spending as (
select customers.customer_id AS customer_id,
sum(order_item.price + order_item.freight_value) AS total_spending
from customers
join orders on customers.customer_id = orders.customer_id 
join order_item on order_item.order_id = orders.order_id
group by customers.customer_id)

select top 5 customer_id, total_spending,
Rank() over( order by total_spending desc ) as ranking
from customer_spending 

-- highest spending customer inside each city  
WITH customer_spending AS(
    SELECT  customers.customer_id,
    customers.customer_city AS city,
 SUM(order_item.price + order_item.freight_value)
    AS total_spending
 FROM customers
 JOIN orders ON customers.customer_id = orders.customer_id
JOIN order_item ON orders.order_id = order_item.order_id
 GROUP BY 
    customers.customer_id,
    customers.customer_city),

 ranking as (
SELECT *,
RANK() OVER (
    PARTITION BY city
    ORDER BY total_spending DESC) AS ranks
FROM customer_spending)

select * from ranking
where
ranks= 1;

-- customers whose spending is greater than average customer spending

WITH customer_spending AS (select customers.customer_id AS customer_id,
sum (order_item.price + order_item.freight_value) AS total_spending
from customers

join orders on customers.customer_id = orders.customer_id 
join order_item on orders.order_id = order_item.order_id
group by customers.customer_id)

select * from customer_spending 
where total_spending > (select avg (total_spending) from customer_spending);

-- customers who spend more than the avg spending of their own city ***

WITH customer_spending AS( SELECT customers.customer_id,
    customers.customer_city AS city,
SUM(order_item.price + order_item.freight_value) AS total_spending
FROM customers
JOIN orders ON customers.customer_id = orders.customer_id
JOIN order_item ON orders.order_id = order_item.order_id
 GROUP BY  customers.customer_id, customers.customer_city )

SELECT * FROM customer_spending cs1
WHERE total_spending >( SELECT AVG(cs2.total_spending)
 FROM customer_spending cs2
 WHERE cs2.city = cs1.city);

 -- products that were ordered at least once
 SELECT * FROM product p
 WHERE EXISTS
(SELECT 1
 FROM order_item oi
 WHERE oi.product_id = p.product_id);

 select order_id, coalesce(CAST( order_delivered_customer_date AS VARCHAR), 'pending') AS DD
 from orders
 